version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    command: sh -c "echo $PATH && pnpm dev"

    ports:
      - 3000:3000
    
    volumes:
      - ./frontend/:/code/
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    
    working_dir: /code/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/code/
      - static:/code/static/
      - media:/code/media/
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    
    ports:
      - 8080:80
    
    volumes:
      - static:/backend/static/
      - media:/backend/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    

volumes:
  static:
  media: